### ISSUE TITLE
PhysicalComponent.get_kind () return en exception

### ISSUE THREAD

**Issue by MateuszMe** [labs4capella/python4capella#113]
Hi,

I play a little with Python4Capella addon and I think I found a bug. When I'm trying to use function get_kind() on PhysicalComponent I received an exception error (I put received message bellow). I'm calling function in proper way, for example get_is_human from same class work well, so I reject this possibility. ​I'll tried to found source of bug on my self, but I'm not really experienced in Java or Python. I check briefly code and I'm pretty sure that this is not a problem related to my platform / software versions, but strictly to library. 

Software / Hardware Specification:
Capella 5.1.0
Python4Capella 1.0.1.202112131006
Python 3.7.12_1
MacOS 11.6, ARM M1

Error message:
```
py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File "/Applications/Capella.app/Contents/Eclipse/plugins/org.eclipse.ease.lang.python.py4j_0.7.0.I201907020902/pysrc/ease_py4j_main.py", line 199, in runcode
    exec(compiled, self.locals)
  File "L/Python4Capella/sample_scripts/BomGeneration.py", line 50, in <module>
    except ImportError:
  File "L/Python4Capella/sample_scripts/BomGeneration.py", line 37, in browsePc
    from six import string_types as _pyease_string_types
  File "L/Python4Capella/simplified_api/capella.py", line 1706, in get_kind
  File "L/Python4Capella/simplified_api/capella.py", line 114, in get_class
    for k, v in value.items()
  File "/Applications/Capella.app/Contents/Eclipse/plugins/py4j-python_0.10.9.3-bnd-2odeag/src/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Applications/Capella.app/Contents/Eclipse/plugins/py4j-python_0.10.9.3-bnd-2odeag/src/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling o44.eClass. Trace:
py4j.Py4JException: Method eClass([]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.sendCommand(ClientServerConnection.java:244)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:384)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:356)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:106)
	at com.sun.proxy.$Proxy25.executeScript(Unknown Source)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.internalExecute(Py4jScriptEngine.java:236)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.execute(Py4jScriptEngine.java:226)
	at org.eclipse.ease.AbstractScriptEngine.inject(AbstractScriptEngine.java:245)
	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Capella.app/Contents/Eclipse/plugins/py4j-python_0.10.9.3-bnd-2odeag/src/py4j/clientserver.py", line 581, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
  File "/Applications/Capella.app/Contents/Eclipse/plugins/org.eclipse.ease.lang.python.py4j_0.7.0.I201907020902/pysrc/ease_py4j_main.py", line 335, in executeScript
    return self.executeCommon(code_text, self.interp.runcode, filename)
  File "/Applications/Capella.app/Contents/Eclipse/plugins/org.eclipse.ease.lang.python.py4j_0.7.0.I201907020902/pysrc/ease_py4j_main.py", line 313, in executeCommon
    execution_result = code_exec(code_text, filename)
  File "/Applications/Capella.app/Contents/Eclipse/plugins/org.eclipse.ease.lang.python.py4j_0.7.0.I201907020902/pysrc/ease_py4j_main.py", line 213, in runcode
    except Exception:
TypeError: catching classes that do not inherit from BaseException is not allowed

	at py4j.Protocol.getReturnValue(Protocol.java:476)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:108)
	at com.sun.proxy.$Proxy25.executeScript(Unknown Source)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.internalExecute(Py4jScriptEngine.java:236)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.execute(Py4jScriptEngine.java:226)
	at org.eclipse.ease.AbstractScriptEngine.inject(AbstractScriptEngine.java:245)
	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by ylussaud** [comment]
This is a bug, the PhysicalComponentKind is an enumeration and doesn't have a method eClass() in Java. You can replace the PhysicalComponent.get_kind() method with:

        def get_kind(self):
            """
            """
            value =  self.get_java_object().getKind()
            if value is None:
                return value
            else:
                return value.getName()

It will return the kind as a String. Please keep this issue opened, I will close it when the fix is done on our side.
We should also fix the setter. This might also need to be done on other get_kind() methods.

The second exception can be fixed by renaming Exception to CapellaException in the capella.py file. see bug #109.

**Comment by MateuszMe** [comment]
Thanks for your reply, this change fixed my problem (first exception).

About second exception - it automatically disappear after changing get_kind class so I didn't need to rename it right now (but maybe I'll need to do this later, when I faced this exception again).
