### ISSUE TITLE
Relation "contextualElementForDiagrams" defined on EObject does not work

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#19]
Trying to use the relation "contextualElementForDiagrams" on a PhysicalFunction of IFE model get the following error.

Note : does not work even if auto test provide an OK result for this...

java.lang.IllegalStateException: org.polarsys.capella.core.semantic.queries.sirius.annotation.eoi.RepresentationToContextualElement query can't be loaded.
	at org.eclipse.python4capella.modules.CapellaModule.callQuery(CapellaModule.java:52)
	at org.eclipse.python4capella.modules.SiriusModule.getContextualElementForDiagrams(SiriusModule.java:363)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.sendCommand(ClientServerConnection.java:244)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:384)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:356)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:106)
	at com.sun.proxy.$Proxy30.executeScript(Unknown Source)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.internalExecute(Py4jScriptEngine.java:236)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.execute(Py4jScriptEngine.java:226)
	at org.eclipse.ease.AbstractScriptEngine.inject(AbstractScriptEngine.java:245)
	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.polarsys.capella.core.semantic.queries.sirius.annotation.eoi.RepresentationToContextualElement cannot be found by org.eclipse.python4capella_0.1.0.202107161458
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.python4capella.modules.CapellaModule.callQuery(CapellaModule.java:48)
	... 20 more

**Comment by ylussaud** [comment]
This issue seems related to older versions of Capella, It works with Capella 6.x.
