### ISSUE TITLE
Support modification of Capella model

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#20]
Trying to use the "set" methods defined in the Python API, we get the following error:

java.lang.IllegalStateException: Cannot modify resource set without a write transaction
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.assertWriting(TransactionChangeRecorder.java:349)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.appendNotification(TransactionChangeRecorder.java:303)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.processObjectNotification(TransactionChangeRecorder.java:285)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.notifyChanged(TransactionChangeRecorder.java:241)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.polarsys.capella.common.data.modellingcore.impl.AbstractNamedElementImpl.setName(AbstractNamedElementImpl.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.sendCommand(ClientServerConnection.java:244)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:384)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:356)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:106)
	at com.sun.proxy.$Proxy30.executeScript(Unknown Source)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.internalExecute(Py4jScriptEngine.java:236)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.execute(Py4jScriptEngine.java:226)
	at org.eclipse.ease.AbstractScriptEngine.inject(AbstractScriptEngine.java:245)
	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ylussaud** [comment]
I added 3 methods to CapellaModel:
- start_transaction()
- commit_transaction()
- rollback_transaction()

You can use them like this

```python
model = CapellaModel(aird_path)

# gets the SystemEngineering and print its name
se = model.get_system_engineering()
print(se.get_name())

model.start_transaction()
try:
    se.set_name("Toto")
except:
    model.rollback_transaction()
    raise
else:
    model.commit_transaction()

print(se.get_name())
```
