### ISSUE TITLE
Relation "representingDiagrams" defined on EObject does not work

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#21]
Trying to use the relation "representingDiagrams" on different type of elements of IFE model get the following error.

Note : does not work even if auto test provide an OK result for this...

java.lang.ClassCastException: org.eclipse.sirius.table.business.internal.metamodel.spec.DTargetColumnSpec cannot be cast to org.eclipse.sirius.diagram.DDiagramElement
	at org.eclipse.python4capella.modules.SiriusModule.getRepresentedElements(SiriusModule.java:184)
	at org.eclipse.python4capella.modules.SiriusModule.getRepresentingDiagrams(SiriusModule.java:341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.sendCommand(ClientServerConnection.java:244)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:384)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:356)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:106)
	at com.sun.proxy.$Proxy30.executeScript(Unknown Source)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.internalExecute(Py4jScriptEngine.java:236)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.execute(Py4jScriptEngine.java:226)
	at org.eclipse.ease.AbstractScriptEngine.inject(AbstractScriptEngine.java:245)
	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ylussaud** [comment]
This exception has been fixed see https://github.com/labs4capella/python4capella/issues/24

Python tests focus only on testing the link between the Python world and the Java world.
