### ISSUE TITLE
Constructors (init methods) throw an error when passing a JavaObject that is not an instance of the expected type.

### ISSUE THREAD

**Issue by ylussaud** [labs4capella/python4capella#237]
The following code:
```
lf = LogicalFunction()
pf = PhysicalFunction(lf)
```
will raise:
```
org.eclipse.ease.ScriptExecutionException: Traceback (most recent call last):
  File "workspace://Python4Capella/sample_scripts/test.py", line 23, in <module>
    from py4j.clientserver import ClientServer as _pyease_ClientServer
  File "workspace://Python4Capella/simplified_api/capella.py", line 7424, in __init__
  File "/home/development/bin/Python4Capella/capella-7.0.0-Python4Capella/capella/plugins/py4j-python_0.10.9.5-bnd-2odeag/src/py4j/java_gateway.py", line 1313, in __call__
    args_command, temp_args = self._build_args(*args)
  File "/home/development/bin/Python4Capella/capella-7.0.0-Python4Capella/capella/plugins/py4j-python_0.10.9.5-bnd-2odeag/src/py4j/java_gateway.py", line 1283, in _build_args
    [get_command_part(arg, self.pool) for arg in new_args])
  File "/home/development/bin/Python4Capella/capella-7.0.0-Python4Capella/capella/plugins/py4j-python_0.10.9.5-bnd-2odeag/src/py4j/java_gateway.py", line 1283, in <listcomp>
    [get_command_part(arg, self.pool) for arg in new_args])
  File "/home/development/bin/Python4Capella/capella-7.0.0-Python4Capella/capella/plugins/py4j-python_0.10.9.5-bnd-2odeag/src/py4j/protocol.py", line 298, in get_command_part
    command_part = REFERENCE_TYPE + parameter._get_object_id()
AttributeError: 'LogicalFunction' object has no attribute '_get_object_id'
```
Which is not very clear for the end user. 
The code of the constructor could be changed to raise a meaningful error:
```
        elif isinstance(java_object, JavaObject):
            if isinstance(java_object, PhysicalFunction):
                JavaObject.__init__(self, java_object.get_java_object())
            else:
                raise AttributeError("Passed object is not a PhysicalFunction: " + str(type(java_object)))
```

**Comment by ylussaud** [comment]
In fact the we should make sure the object is a refeence to a Java Object before calling the isInstance() of the e_class.
