### ISSUE TITLE
openpyxl component import problems

### ISSUE THREAD

**Issue by maevans12** [labs4capella/python4capella#84]
### Discussed in https://github.com/labs4capella/python4capella/discussions/83

<div type='discussions-op-text'>

<sup>Originally posted by **maevans12** November  1, 2021</sup>
Has there been any issues with the use of openpyxl?  I'm running Capella 5.1.0, python interpreter 3.7 and when I try to run the sample script "import_physical_components_from_xlsx.py", or anything else that runs the "from openpyxl import *" statement, something doesn't return from completing this import statement.  In the Progress terminal, it seems that something in Sirius_API.py is hanging.  

![image](https://user-images.githubusercontent.com/18238582/139747509-51f8d456-6b35-4318-a26b-bb4123150ba2.png)

![image](https://user-images.githubusercontent.com/18238582/139747593-2ce29537-811e-4df9-b4c4-d10452f3a97d.png)

NOTE:  Yes the images show a different script name than "import_physical_components_from_xlsx.py".  I copied the contents of ""import_physical_components_from_xlsx.py" to a different script to debug in a different project.  Both scripts behave the same.
</div>

**Comment by ylussaud** [comment]
Are you using the provided [Pyton37.zip](https://github.com/labs4capella/python4capella/releases/download/1.0.0/Python37.zip) file ? openpyxl is installed with the Python interpreter.

Do you have any error message that could help ?

**Comment by maevans12** [comment]
Yes, I'm using the python environment from the python37.zip.  

No other error messages appear.  (Or, in other words, the screenshots above show you what I see..console just shows the entry into the "from openpyxl import *" line.  The process just seems to hang.  

Where should I look for any other messages or logs?

**Comment by maevans12** [comment]
Actually, here are the 2 error messages in the log.

![image](https://user-images.githubusercontent.com/18238582/140087120-4aa09a3f-93d7-483a-952e-12c53f72e4aa.png)

![image](https://user-images.githubusercontent.com/18238582/140087190-a4c5cb49-29e5-400c-a915-fe40b82d5e3a.png)

**Comment by maevans12** [comment]
eclipse.buildId=unknown
java.version=14.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ease
Error
Wed Nov 03 10:07:04 CDT 2021
The method name "zip" from the module "__EASE_MOD_org_eclipse_ease_modules_platform_ResourcesModule" can not be wrapped because it's name is reserved

**Comment by maevans12** [comment]
eclipse.buildId=unknown
java.version=14.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ease.lang.python
Error
Wed Nov 03 10:07:04 CDT 2021
The method name "zip" from the module "__EASE_MOD_org_eclipse_ease_modules_platform_ResourcesModule" can not be wrapped because it's name is reserved

**Comment by ylussaud** [comment]
I don't think this is related... I added a release with some fixes related to the Capella 5.1.0 compatibility. Can you check if it fix your issues ?

[2021-11-03](https://github.com/labs4capella/python4capella/releases/tag/2021-11-03)

**Comment by maevans12** [comment]
Well, what I did didn't seem to make any difference (same behavior, same error messages in log).  How I installed this updated was to download the zip file, extract it into the same directory where I had put the last update site SW, then reinstalled the software through capella.

![image](https://user-images.githubusercontent.com/18238582/140169770-6275e9bb-c095-4ab6-b015-9fac4f0c08e5.png)
![image](https://user-images.githubusercontent.com/18238582/140169873-780aed67-9472-43a3-b4a2-43150e1669f4.png)

**Comment by maevans12** [comment]
![image](https://user-images.githubusercontent.com/18238582/140170084-fe0ecdaa-6d90-4a82-834b-88bf680e5252.png)
The last saved images are the versions in my environment for EASE and python4capella.

**Comment by maevans12** [comment]
Additional note, I reverted my installation back to pre-python4capella state and installed 2021-11-03 by itself.  my current installation configuration looks like:
![image](https://user-images.githubusercontent.com/18238582/140174400-d4f94128-49b8-4972-83a9-11932653eabe.png)

Still no success getting the script to run.  The two error messages are provided below.  Curiously, the progress window does not come up so I'm not seeing the same where it looks like it's hanging in Sirious_API.py.  

null
org.eclipse.ease
Error
Wed Nov 03 13:48:42 CDT 2021
The method name "zip" from the module "__EASE_MOD_org_eclipse_ease_modules_platform_ResourcesModule" can not be wrapped because it's name is reserved

null
org.eclipse.ease.lang.python
Error
Wed Nov 03 13:48:42 CDT 2021
The method name "zip" from the module "__EASE_MOD_org_eclipse_ease_modules_platform_ResourcesModule" can not be wrapped because it's name is reserved

**Comment by ylussaud** [comment]
The installation looks good to me.
Can you try to open the Capella project before running the script ? The session opening can be a bit slow looking like it hangs.

**Comment by maevans12** [comment]
I'm not sure I understand what you are asking me to do.  Before I run this script, I have the Capella project open in the Capella perspective.  I then select and run the run configuration for the script file (set up as an EASE script.  See graphic below).

![image](https://user-images.githubusercontent.com/18238582/140305606-a057864c-ec4e-4f5a-b00e-278fda61cfb1.png)

The image I gave you is for my file, but I get the same result if I use the sample script "import_physical_components_from_xlsx.py" that comes with python4capella.

Maybe a better question is, can you replicate this problem on your side?  Am I the only one seeing this issue?  The reason I'm asking is if you are asking me to test this, makes me wonder if this problem exist for you.  If it's only me, then maybe we just need to make sure I'm set up and using this plugin correctly.

**Comment by maevans12** [comment]
I don't know if this helps, but I run my script in the debugger (stepping into the import commands) and things crash consistently when trying to import numpy. Stack trace when things crash is:

py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File "C:\Capella\capella\plugins\py4j-python_0.10.9.2-bnd-2odeag\src\py4j\clientserver.py", line 581, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
  File "<...>", line 424, in run
  File "C:\Capella\Python37\lib\bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "__ref_L/Flex Scripts/Scripts/Read_Excel_File.py_jrxtfytlqy", line 21, in <module>
    import os as _pyease_os
  File "C:\Capella\Python37\lib\site-packages\openpyxl\__init__.py", line 4, in <module>
    from openpyxl.compat.numbers import NUMPY
  File "C:\Capella\Python37\lib\site-packages\openpyxl\compat\__init__.py", line 3, in <module>
    from .numbers import NUMERIC_TYPES
  File "C:\Capella\Python37\lib\site-packages\openpyxl\compat\numbers.py", line 9, in <module>
    import numpy
  File "C:\Capella\Python37\lib\site-packages\numpy\__init__.py", line 119, in <module>
    __NUMPY_SETUP__
  File "<...>", line 231, in trace_dispatch
  File "C:\Capella\Python37\lib\bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "C:\Capella\Python37\lib\bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "<...>", line 271, in user_exception
  File "C:\Capella\capella\plugins\py4j-python_0.10.9.2-bnd-2odeag\src\py4j\java_gateway.py", line 1310, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "C:\Capella\capella\plugins\py4j-python_0.10.9.2-bnd-2odeag\src\py4j\protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling o0.setExceptionStackTrace. Trace:
py4j.Py4JException: Method setExceptionStackTrace([class com.sun.proxy.$Proxy32]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.sendCommand(ClientServerConnection.java:244)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:384)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:356)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:106)
	at com.sun.proxy.$Proxy31.run(Unknown Source)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jDebugger.execute(Py4jDebugger.java:106)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jDebuggerEngine.internalExecute(Py4jDebuggerEngine.java:77)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.execute(Py4jScriptEngine.java:226)
	at org.eclipse.ease.AbstractScriptEngine.inject(AbstractScriptEngine.java:245)
	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)



	at py4j.Protocol.getReturnValue(Protocol.java:476)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:108)
	at com.sun.proxy.$Proxy31.run(Unknown Source)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jDebugger.execute(Py4jDebugger.java:106)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jDebuggerEngine.internalExecute(Py4jDebuggerEngine.java:77)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.execute(Py4jScriptEngine.java:226)
	at org.eclipse.ease.AbstractScriptEngine.inject(AbstractScriptEngine.java:245)
	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Also, the line it crashes on in numpy is 119.
the block of code in numpy is:
try:
    __NUMPY_SETUP__
except NameError:
    __NUMPY_SETUP__ = False

**Comment by maevans12** [comment]
what's interesting is if I try to import, say, pandas, things crash in the say way at the same location.  Again, not sure if this helps, but found it interesting.

**Comment by maevans12** [comment]
Note, if I run a python script outside of the Capella/Eclipse environment (from the command line using simply the "python file.py" type command), everything works fine.  This problem has something to do with the Capella/Eclipse environment.

**Comment by ylussaud** [comment]
I did the following:

unzip a Capella 5.1.0
import IFE example
install the last Python4Capella update site
import the Pyhton4Capella project
configure python interpreters to the Python37.zip
activate developer capabilities
run the script with the following parameter:
"/In-Flight Entertainment System/In-Flight Entertainment System.aird" "/Python4Capella/resources/physical_components.xlsx"

wait a bit for the Capella project to open...
Output:

Read C:/capella-5.1.0.202106150755-win32-win32-x86_64/capella/workspace/Python4Capella/resources/physical_components.xlsx
* Create a new physical component with name NewPhysicalComponent1
* Create a new physical component with name NewPhysicalComponent2
* Create a new physical component with name NewPhysicalComponent3
* Create a new physical component with name NewPhysicalComponent4
* Create a new physical component with name NewPhysicalComponent5
* Create a new physical component with name NewPhysicalComponent6
* Create a new physical component with name NewPhysicalComponent7
* Create a new physical component with name NewPhysicalComponent8
* Create a new physical component with name NewPhysicalComponent9
* Create a new physical component with name NewPhysicalComponent10

Can you try with a new environment and follow the steps described here to see if it helps ?

**Comment by maevans12** [comment]
Unfortunately, this did not work.  

Question, what do you mean by "wait a bit for the Capella project to open..."?  The IFE project was already open (see your 2nd step).  Are you saying the Capella Console?  

BTW, as per my last comment, things seem to be crashing while importing numpy.  If I put things in the debug perspective and step into the import commands, it crashes in the same place with the following stack trace.

py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File "C:\Capella\capella\plugins\py4j-python_0.10.9.2-bnd-2odeag\src\py4j\clientserver.py", line 581, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
  File "<...>", line 424, in run
  File "C:\Capella\Python37\lib\bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "__ref_L/Python4Capella/sample_scripts/import_physical_components_from_xlsx.py_kxfwjqrxay", line 23, in <module>
    from py4j.clientserver import ClientServer as _pyease_ClientServer
  File "C:\Capella\Python37\lib\site-packages\openpyxl\__init__.py", line 4, in <module>
    from openpyxl.compat.numbers import NUMPY
  File "C:\Capella\Python37\lib\site-packages\openpyxl\compat\__init__.py", line 3, in <module>
    from .numbers import NUMERIC_TYPES
  File "C:\Capella\Python37\lib\site-packages\openpyxl\compat\numbers.py", line 9, in <module>
    import numpy
  File "C:\Capella\Python37\lib\site-packages\numpy\__init__.py", line 119, in <module>
    __NUMPY_SETUP__
  File "<...>", line 231, in trace_dispatch
  File "C:\Capella\Python37\lib\bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "C:\Capella\Python37\lib\bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "<...>", line 271, in user_exception
  File "C:\Capella\capella\plugins\py4j-python_0.10.9.2-bnd-2odeag\src\py4j\java_gateway.py", line 1310, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "C:\Capella\capella\plugins\py4j-python_0.10.9.2-bnd-2odeag\src\py4j\protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling o0.setExceptionStackTrace. Trace:
py4j.Py4JException: Method setExceptionStackTrace([class com.sun.proxy.$Proxy30]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.sendCommand(ClientServerConnection.java:244)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:384)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:356)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:106)
	at com.sun.proxy.$Proxy29.run(Unknown Source)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jDebugger.execute(Py4jDebugger.java:106)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jDebuggerEngine.internalExecute(Py4jDebuggerEngine.java:77)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.execute(Py4jScriptEngine.java:226)
	at org.eclipse.ease.AbstractScriptEngine.inject(AbstractScriptEngine.java:245)
	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)



	at py4j.Protocol.getReturnValue(Protocol.java:476)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:108)
	at com.sun.proxy.$Proxy29.run(Unknown Source)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jDebugger.execute(Py4jDebugger.java:106)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jDebuggerEngine.internalExecute(Py4jDebuggerEngine.java:77)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.execute(Py4jScriptEngine.java:226)
	at org.eclipse.ease.AbstractScriptEngine.inject(AbstractScriptEngine.java:245)
	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by maevans12** [comment]
![image](https://user-images.githubusercontent.com/18238582/140414730-8aea424b-8595-4227-b831-02799401fd5c.png)
![image](https://user-images.githubusercontent.com/18238582/140414771-f0b29e48-73ce-4224-8483-d1d3ffd11b13.png)

I also started Capella with the -clean option set.

**Comment by ylussaud** [comment]
To complete the installation of the update site in step 3 you have to restart Capella. After restarting my IFE project Capella session was not opened. And wait a bit means something like 15 seconds. I didn't test the numpy import since it will not help for our issue.
Is there anything happening on your system will launching the script ? like security tool alert ?

**Comment by maevans12** [comment]
OK, I'm now working.  The issue is that you cannot modify the python37 environment AT ALL.  As mentioned earlier, I had used pip to bring in pandas (I'm familiar with that package for .xlsx imports) which pip brought in numpy as a dependency.  With that, the Capella environment crashed because there is a weird reference in the init for openpyxl to numpy that it didn't like (which is what I was tracing).  We should update documentation that this addon is very sensitive to the python environment.  This is kind of a bummer since this will limit future uses of this product.

**Comment by ylussaud** [comment]
did you try installing new Python packages using the method described in the documentation ?

cd Python37
Scripts\pip install [package name]

**Comment by maevans12** [comment]
No, because it doesn't work that way (at least not exactly how it's written).
![image](https://user-images.githubusercontent.com/18238582/140523467-a526cf27-3aa0-45f0-bd8e-451c61e4e2a8.png)

The way I did it was by going to the Python37 directory (the level where the python.exe file is located), then running a standard pip install command.  I.e.

C:\Capella\Python37>python -m pip install pandas

This way works.
![image](https://user-images.githubusercontent.com/18238582/140524198-cd5e89be-755d-4f06-a7ca-6e86d28c9c65.png)

What's interesting, is that even thought I just did this after re-extracting the Python37 .zip, things are still working now in Capella (Capella is with the pre-existing build status where I was seeing errors).  

Now, one thing I noticed earlier, is that the preferences is:
![image](https://user-images.githubusercontent.com/18238582/140524754-be220323-01ce-45ff-9077-20034e333a23.png)

Notice that the packages do not show up in the dialog.  I found this curious so I updated pip.

![image](https://user-images.githubusercontent.com/18238582/140525201-ba53e089-1b45-44ce-a7da-24792b2842d8.png)

After restarting Capella, the packages now show up.
![image](https://user-images.githubusercontent.com/18238582/140525401-3050fc39-962b-40ce-b640-cccf25787aa1.png)

And still, things work.  (Please keep in mind, I'm using the same environment of Capella where things were not working.)

![image](https://user-images.githubusercontent.com/18238582/140525617-e755398e-7d37-4203-990f-3c1b35d8a040.png)

Weird.

**Comment by maevans12** [comment]
They only thing that I have done since then is start capella with the -clean option through a shortcut.

![image](https://user-images.githubusercontent.com/18238582/140526276-a8a534b6-ea60-4538-8cbe-1bb36d1a0f00.png)

**Comment by maevans12** [comment]
Anyway, things are working...  

Thanks for your time.  Let me know if my way up updating the python37 environment has some pitfalls I'm not aware of.

**Comment by maevans12** [comment]
BTW, I'm not adding python37 to my system path because I use python 3.9 for other development.  Maybe somewhere, Capella (Eclipse/EASE) got confused and tried to use that, but I'm not sure how.  I'm kept (and am keeping) Capella pointing only to python37.

**Comment by ylussaud** [comment]
It seems like there is a link with the path where I created this Python environment that produce an error (c:\users\ylussaud\...).
I should update the documentation to update pip and use your command line.
And the version of EASE we are using doesn't support Python 3.8 and above. At some point we will update the version EASE we are using.

And thank you for your time too... Python4Capella is still pretty new and need some improvements.
